spring.application.name=backend

# Server
server.port=8080

# Database ? switch between MySQL and PostgreSQL by commenting/uncommenting

# MySQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PWD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# PostgreSQL (comment out MySQL above and uncomment below)
# spring.datasource.url=jdbc:postgresql://localhost:5432/contextsnap_db
# spring.datasource.username=postgres
# spring.datasource.password=yourpassword
# spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=${JWT_KEY}
jwt.expiration=86400000

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL}
spring.mail.password=${GMAIL_PWD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# CORS
frontend.url=http://localhost:5173